name: pink_balancer
channels:
    - conda-forge
dependencies:
    - gin-config >=0.5.0
    - meshcat-shapes >=0.3.0
    - pink >=3.0.0,<4
    - pinocchio >=3.1.0,<4
    - qpmpc >=3.0.1,<4
    - qpsolvers >=4.2.0,<5
    - upkie ==8.0.0
